---
engines:
  fixme:
    enabled: true
  checkstyle:
    enabled: true
    channel: "beta"
    checks:
          com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
            enabled: false
  pmd:
    enabled: true
    channel: "beta"
ratings:
  paths:
  - "**.java"
exclude_paths:
 - src/test/
